-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categorias
(
    id integer NOT NULL DEFAULT nextval('categorias_id_seq'::regclass),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categorias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tareas
(
    id integer NOT NULL DEFAULT nextval('tareas_id_seq'::regclass),
    texto character varying(255) COLLATE pg_catalog."default" NOT NULL,
    completada boolean NOT NULL DEFAULT false,
    fecha date NOT NULL DEFAULT now(),
    categoria_id integer,
    CONSTRAINT tareas_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tareas
    ADD CONSTRAINT fk FOREIGN KEY (categoria_id)
    REFERENCES public.categorias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;